### ISSUE TITLE
Matrix package installation fails on macOS (libintl.h not found)

### ISSUE THREAD

**Issue by FBartos** [FBartos/RoBMA#50]
The GitHub Actions workflow is failing on macOS when attempting to install the Matrix R package. The installation process throws a fatal error due to a missing libintl.h header file, which is required for building the package from source.

**Relevant log excerpt:**
```
Error installing package 'Matrix':
- Installing Matrix ... FAILED
...
./Mdefines.h:41:11: fatal error: 'libintl.h' file not found
 # include <libintl.h>
           ^~~~~~~~~~~
1 error generated.
make: *** [Csparse.o] Error 1
ERROR: compilation failed for package ‘Matrix’
* removing ‘/Users/runner/work/RoBMA/RoBMA/renv/staging/1/Matrix’
install of package 'Matrix' failed [error code 1]
```
Link to failing job:
https://github.com/FBartos/RoBMA/actions/runs/15529967068/job/43716636770

**Steps to reproduce:**
1. Run the workflow on macOS using the provided configuration.
2. Observe the failure during the Matrix package installation.

**Possible solution:**
Install the gettext package and link it to provide the missing header:
```yaml
- name: Install Dependencies (macOS)
  if: runner.os == 'macOS'
  run: |
    brew update
    brew install jags gettext
    brew link --force gettext
```
Add the above step to the macOS section of your workflow before attempting to install R package dependencies.
